name: Coverage Badge
description: Generate coverage.py badge
author: tj-actions
inputs:
  token:
    description: 'GITHUB_TOKEN or a Repo scoped PAT'
    required: true
    default: ${{ github.token }}
  output:
    description: 'Output path to write the badge.'
    required: true
    default: 'coverage.svg'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
branding:
  icon: menu
  color: white
