name: Coverage Badge
description: Generate coverage.py badge
author: tj-actions
inputs:
  output:
    description: 'Output path to write the badge.'
    required: true
    default: 'coverage.svg'
  overwrite:
    description: 'Overwrite existing.'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - id: coverage-badge
      run: |
        pip install -U coverage-badge
        bash entrypoint.sh
      shell: bash
branding:
  icon: menu
  color: white
