name: coverage.py badge
description: Generate coverage.py badge
author: tj-actions
inputs:
  output:
    description: 'Output path to write the badge.'
    required: true
    default: 'coverage.svg'
  overwrite:
    description: 'Overwrite existing.'
    required: true
    default: 'true'

runs:
  using: 'composite'
  steps:
    - id: coverage-badge
      run: |
        pip install -U coverage-badge
        EXTRA_ARGS=""

        if [[ '${{ inputs.overwrite }}' == 'true'  ]]; then
          EXTRA_ARGS+='-f'
        fi

        coverage-badge "$EXTRA_ARGS" -o "${{ inputs.output }}"
      shell: bash
branding:
  icon: menu
  color: white
