name: coverage.py Badge
description: Generate coverage.py badge
author: tj-actions
inputs:
  output:
    description: 'Output path to write the badge.'
    required: true
    default: 'coverage.svg'
  overwrite:
    description: 'Overwrite existing.'
    required: true
    default: 'true'

runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: menu
  color: white
